data:
  raw_data_dir: "D:\\Project\\data"
  archive_name: "archive.zip"
  extract_dir: "D:\\Project\\data\\extracted"
  sample_size: 50000

features:
  target: "ArrDel15"
  numeric:
    - "Month"
    - "DayOfWeek"
    - "CRSDepTime"
    - "CRSArrTime"
    - "CRSElapsedTime"
    - "Distance"
    - "DepDelay"
  categorical:
    - "Reporting_Airline"
    - "Origin"
    - "Dest"
    - "DepTimeBlk"
    - "ArrTimeBlk"
  drop_threshold: 0.60

model:
  test_size: 0.20
  random_state: 42
  save_dir: "models"
  random_forest:
    n_estimators: [50]
    max_depth: [10]
    min_samples_split: [2]
  gradient_boosting:
    n_estimators: [50]
    learning_rate: [0.1]
    max_depth: [3]

mlflow:
  tracking_uri: "https://dagshub.com/Prosad-h/Delay-performance.mlflow/"
  experiment_name: "flight-delay-prediction"
  dagshub_repo_owner: "Prosad-h"
  dagshub_repo_name: "Delay-performance"

server:
  host: "0.0.0.0"
  port: 5000
  debug: false
